### ISSUE TITLE
Improve showing functions

### ISSUE THREAD

**Issue by UnkindPartition** [Bodigrim/smallcheck#11]
First, provide a Fun datatype which knows about the function structure and show it instead.

Second, implement either function shrinking as described by Klaessen, or lazy-smallcheck-like shrinking.

**Comment by Bodigrim** [comment]
I think that modern QuickCheck-like frameworks with powerful shrinking such as [`falsify`](https://hackage.haskell.org/package/falsify) offer a smoother user experience than `smallcheck`. I'll carry on with life support of `smallcheck`, but not really interested in changing things. Closing, won't do.
