### ISSUE TITLE
Better Char/String instances

### ISSUE THREAD

**Issue by UnkindPartition** [Bodigrim/smallcheck#12]
See [this reddit thread](http://www.reddit.com/r/haskell/comments/17idma/how_to_write_unmaintainable_haskell_code/c866olo?context=3).

To do this, we need to decide:
- what kinds of characters we want to generate, and at which rate
- make newtype wrappers for some common cases? ASCII, Printable, Unicode?

**Comment by gspia** [comment]
Hi, 
Is there new thought are plans with this issue? 
I'm having a Text-based test where the current way of generating chars 'a'..'z' is enough. Anyhow, would there be any chances of having Text-instances based on this generating mechanism. 

Even though the text-based instance would suffer from the very same problems mentioned above, I think that, as the Text is de-facto standard way to do things, there could be instances for it. And even if not ideal right away, things could be improved given time (hmm, or is there a danger of locking in into wrong lib-ui in case of willing to avoid breaking changes later).

I think that the approach giving wrappers for common cases would be helpful. (Even though I cannot see right away, how that would look / what kind of things it would mean for the users of this lib.)

**Comment by feuerbach** [comment]
>  Is there new thought are plans with this issue?

Not really.

> I'm having a Text-based test where the current way of generating chars 'a'..'z' is enough. 

In that case, this is probably not the issue you are looking for.

Does https://hackage.haskell.org/package/smallcheck-series-0.6/docs/Test-SmallCheck-Series-Text.html help?

**Comment by gspia** [comment]
Ah, thank you! I can use that package!

**Comment by Bodigrim** [comment]
I think that modern QuickCheck-like frameworks with powerful shrinking such as [`falsify`](https://hackage.haskell.org/package/falsify) offer a smoother user experience than `smallcheck`. I'll carry on with life support of `smallcheck`, but not really interested in changing things. Closing, won't do.
