### ISSUE TITLE
Limit the number of tests

### ISSUE THREAD

**Issue by UnkindPartition** [Bodigrim/smallcheck#13]
twanvl [writes](http://www.reddit.com/r/haskell/comments/18uhfy/announcing_smallcheck_10/c8igcjg):

> The default smallCheck could just have a limit on the number of testcases and report the depth searched:
> 
> ```
> λ> smallCheck prop_abc
> Ok, stopped after 1000 tests, tested all values up to depth 3.
> ```

**Comment by Bodigrim** [comment]
This has been implemented in `tasty-smallcheck-0.8.2`, https://github.com/UnkindPartition/tasty/pull/282.
