### ISSUE TITLE
Generically derived Serial instance for mutually recursive data type causes infinite loop

### ISSUE THREAD

**Issue by runeksvendsen** [Bodigrim/smallcheck#46]
Hi there,

Firstly, thanks for making this wonderful library!

When automagically deriving `Serial` instances for `Generic` data types that are recursive, smallcheck seems to go into an infinite loop when trying to generate values of this type.

Here is a source repository/commit that exhibits this symptom: https://github.com/runeksvendsen/rule-lang/commit/b2f36ef6fb130a2e429de3d22d08f76b76c60a65

Steps to reproduce:

```
git clone https://github.com/runeksvendsen/rule-lang.git
cd rule-lang
git checkout b2f36ef6fb130a2e429de3d22d08f76b76c60a65
stack test
```

The above will hang indefinitely using 100% CPU without generating any values.

This is fixed by manually creating `Serial` instances that, for some type `A`, applies `decDepth` to any generator that ends up creating an `A`.

**Comment by Bodigrim** [comment]
Honestly, the linked commit with 945 additions and 631 deletions is not something I can easily investigate. 

In general `smallcheck` seems to be capable to generate `Serial` for `Generic` data types that are recursive:

```haskell
> :set -XDeriveGeneric -XDeriveAnyClass
> import GHC.Generics (Generic)
> data List a = Nil | Cons a (List a) deriving (Show, Generic)
> instance (Monad m, Serial m a) => Serial m (List a)
> listSeries 5 :: [List ()]
[Nil,Cons () Nil,Cons () (Cons () Nil),Cons () (Cons () (Cons () Nil)),Cons () (Cons () (Cons () (Cons () Nil)))]
```

Do you possibly have a smaller example?

**Comment by Bodigrim** [comment]
Feel free to reopen if you come with a smaller reproducer.
