### ISSUE TITLE
depth for generics is broken

### ISSUE THREAD

**Issue by kuribas** [Bodigrim/smallcheck#47]
when using Generics, and incorrect depth is used:

```haskell
> data Test = Test1 Int | Test2 String | Test3 String deriving (Generic, Show)
> instance Monad m => Serial m Test
> list 1 series :: [Test]
[Test1 0]
> list 2 series :: [Test]
[Test1 0,Test2 "",Test1 1,Test3 "",Test1 (-1)]
```
it looks like it's using the depth of the Rep Test, instead of the depth of Test.

**Comment by Bodigrim** [comment]
Could you please clarify what exactly is broken here?

**Comment by kuribas** [comment]
well, I would expect the different constructors to appear equally in the generated list, but that doesn't seem the case.  For example Test1 1 comes before Test3 "".

**Comment by Bodigrim** [comment]
I don't think this has anything to do with `Generic`. This is just a consequence of instances for `Int` and `String`:

```haskell
> listSeries 0 :: [Int]
[0]
> listSeries 0 :: [String]
[]
> listSeries 1 :: [Int]
[0,1,-1]
> listSeries 1 :: [String]
[""]
```

**Comment by kuribas** [comment]
Ah, indeed.  Why do the instances for `Int` and `String` behave differently (one is empty at 0 level, the other not)?

**Comment by Bodigrim** [comment]
Because `Int` is considered to be a primitive type, but `String` is `[Char]`, so you need to spend at least one unit of depth to get `[]`.
